# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e997c34c1380bcdb7700a20fee8c6e5ef85af430949bfdb027ba7c81338a63acce111bb269714e776a624ff062a36054c709f350b44137b45d675b7f1043c377

test:
  secret_key_base: c14c354c23fd483630b6de793287ced8c6e869a9f18adf7f3f0e172e6a17899a9dd0bd574586914ebae4e8832847885e79fb859c233fb2a70233b3b90bbc8343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
